### ISSUE TITLE
easier configless bi-directional setup

### ISSUE THREAD

**Issue by fbernier** [hossbeast/meshboard#1]
Hey,

Thanks for meshboard! It seems quite useful and I'm trying to set it up right now.

I understand it aims at solving the mesh use case which sounds great, but I feel like there could be a way to make is easier to quickly set up a bi-directional clipboard between two hosts.

Something like: `meshboard ssh someip` or `meshboard mosh someip`

I don't know anything about the implementation yet but do you think that sounds feasible?

**Comment by hossbeast** [comment]
Hey, glad to hear of your interest.

Just so we're on the same page, a two node mesh using say, udp sockets would be as simple as this

A
```
sources : {
 {
  udp
  pubkey : foo
  bind : "192.168.0.10:5000" # local address
  connect : "192.168.0.11" # remote address
 }
}
sinks : [
 {
  udp
  pubkey : foo
  bind : "192.168.0.10" # local address
  connect : "192.168.0.11:5001" # remote address
 }
]
```

B
```
sources : {
 {
  udp
  pubkey : bar
  bind : "192.168.0.11:5001" # local address
  connect : "192.168.0.10" # remote address
 }
}
sinks : [
 {
  udp
  pubkey : bar
  bind : "192.168.0.11" # local address
  connect : "192.168.0.10:5000" # remote address
 }
]
```

Then, to actually interact with the clipboard, you'd also need to add xorg/wayland nodes to those as well.

I guess it is kind of cumbersome to hack out the config files, but once you've got them, its pretty much "just run the program" from then on.

I could see a use case for a guided command that creates the config files, then perhaps ssh's to each machine, creates the file, and starts the daemon?

**Comment by hossbeast** [comment]
closing, remove moved to sr.ht
